CREATE database apache_abdera;
CREATE database apache_accumulo;
CREATE database apache_ace;
CREATE database apache_activemq;
CREATE database apache_airavata;
CREATE database apache_airflow_incubator;
CREATE database apache_allura;
CREATE database apache_ambari;
CREATE database apache_annotator_incubator;
CREATE database apache_ant;
CREATE database apache_any23;
CREATE database apache_apex;
CREATE database apache_apr;
CREATE database apache_archiva;
CREATE database apache_archive;
CREATE database apache_argus;
CREATE database apache_ariatosca_incubator;
CREATE database apache_aries;
CREATE database apache_arrow;
CREATE database apache_asf_wide;
CREATE database apache_asterixdb;
CREATE database apache_atlas;
CREATE database apache_attic;
CREATE database apache_aurora;
CREATE database apache_avalon;
CREATE database apache_avro;
CREATE database apache_axis;
CREATE database apache_bahir;
CREATE database apache_batchee_incubator;
CREATE database apache_beam;
CREATE database apache_beehive;
CREATE database apache_bigtop;
CREATE database apache_bloodhound;
CREATE database apache_bookkeeper;
CREATE database apache_brooklyn;
CREATE database apache_buildr;
CREATE database apache_bval;
CREATE database apache_calcite;
CREATE database apache_camel;
CREATE database apache_carbondata;
CREATE database apache_cassandra;
CREATE database apache_cayenne;
CREATE database apache_celix;
CREATE database apache_chemistry;
CREATE database apache_chukwa;
CREATE database apache_clerezza;
CREATE database apache_click;
CREATE database apache_climate;
CREATE database apache_cloudstack;
CREATE database apache_cmda_incubator;
CREATE database apache_cocoon;
CREATE database apache_commons;
CREATE database apache_commonsrdf;
CREATE database apache_community;
CREATE database apache_concerted_incubator;
CREATE database apache_continuum;
CREATE database apache_cordova;
CREATE database apache_corinthia_incubator;
CREATE database apache_cotton_incubator;
CREATE database apache_couchdb;
CREATE database apache_creadur;
CREATE database apache_crunch;
CREATE database apache_ctakes;
CREATE database apache_curator;
CREATE database apache_cxf;
CREATE database apache_datafu_incubator;
CREATE database apache_db;
CREATE database apache_deltacloud;
CREATE database apache_deltaspike;
CREATE database apache_devicemap;
CREATE database apache_directmemory;
CREATE database apache_directory;
CREATE database apache_distributedlog_incubator;
CREATE database apache_drill;
CREATE database apache_eagle;
CREATE database apache_edgent_incubator;
CREATE database apache_empire;
CREATE database apache_esme;
CREATE database apache_etch;
CREATE database apache_excalibur;
CREATE database apache_falcon;
CREATE database apache_felix;
CREATE database apache_fineract;
CREATE database apache_fleece;
CREATE database apache_flex;
CREATE database apache_flink;
CREATE database apache_flume;
CREATE database apache_fluo_incubator;
CREATE database apache_forrest;
CREATE database apache_freemarker_incubator;
CREATE database apache_gearpump_incubator;
CREATE database apache_geode;
CREATE database apache_geronimo;
CREATE database apache_giraph;
CREATE database apache_gobblin_incubator;
CREATE database apache_gora;
CREATE database apache_gossip_incubator;
CREATE database apache_griffin_incubator;
CREATE database apache_groovy;
CREATE database apache_guacamole_incubator;
CREATE database apache_gump;
CREATE database apache_hadoop;
CREATE database apache_hama;
CREATE database apache_harmony;
CREATE database apache_hawq_incubator;
CREATE database apache_hbase;
CREATE database apache_hc;
CREATE database apache_hdt_incubator;
CREATE database apache_helix;
CREATE database apache_hive;
CREATE database apache_hivemall_incubator;
CREATE database apache_hivemind;
CREATE database apache_horn_incubator;
CREATE database apache_htrace_incubator;
CREATE database apache_httpd;
CREATE database apache_ibatis;
CREATE database apache_ignite;
CREATE database apache_impala_incubator;
CREATE database apache_incubator;
CREATE database apache_infra;
CREATE database apache_iota_incubator;
CREATE database apache_isis;
CREATE database apache_jackrabbit;
CREATE database apache_jakarta;
CREATE database apache_james;
CREATE database apache_jclouds;
CREATE database apache_jena;
CREATE database apache_jmeter;
CREATE database apache_johnzon;
CREATE database apache_joshua_incubator;
CREATE database apache_jspwiki;
CREATE database apache_juddi;
CREATE database apache_juneau_incubator;
CREATE database apache_kafka;
CREATE database apache_karaf;
CREATE database apache_knox;
CREATE database apache_kudu;
CREATE database apache_kylin;
CREATE database apache_labs;
CREATE database apache_lens;
CREATE database apache_lenya;
CREATE database apache_libcloud;
CREATE database apache_livy_incubator;
CREATE database apache_logging;
CREATE database apache_lucene;
CREATE database apache_lucenenet;
CREATE database apache_lucy;
CREATE database apache_madlib_incubator;
CREATE database apache_mahout;
CREATE database apache_manifoldcf;
CREATE database apache_marmotta;
CREATE database apache_maven;
CREATE database apache_mesos;
CREATE database apache_metamodel;
CREATE database apache_metron;
CREATE database apache_milagro_incubator;
CREATE database apache_mina;
CREATE database apache_mnemonic_incubator;
CREATE database apache_mrql_incubator;
CREATE database apache_mrunit;
CREATE database apache_mxnet_incubator;
CREATE database apache_myfaces;
CREATE database apache_mynewt;
CREATE database apache_myriad_incubator;
CREATE database apache_netbeans_incubator;
CREATE database apache_nifi;
CREATE database apache_nutch;
CREATE database apache_ode;
CREATE database apache_ofbiz;
CREATE database apache_olingo;
CREATE database apache_oltu;
CREATE database apache_omid_incubator;
CREATE database apache_onami;
CREATE database apache_oodt;
CREATE database apache_oozie;
CREATE database apache_openaz_incubator;
CREATE database apache_openejb;
CREATE database apache_openjpa;
CREATE database apache_openmeetings;
CREATE database apache_opennlp;
CREATE database apache_openoffice;
CREATE database apache_openwebbeans;
CREATE database apache_openwhisk_incubator;
CREATE database apache_optiq;
CREATE database apache_orc;
CREATE database apache_parquet;
CREATE database apache_pdfbox;
CREATE database apache_perl;
CREATE database apache_phoenix;
CREATE database apache_pig;
CREATE database apache_pirk_incubator;
CREATE database apache_pivot;
CREATE database apache_poi;
CREATE database apache_polygene;
CREATE database apache_ponymail_incubator;
CREATE database apache_portals;
CREATE database apache_predictionio_incubator;
CREATE database apache_provisionr_incubator;
CREATE database apache_pulsar_incubator;
CREATE database apache_qpid;
CREATE database apache_quarks;
CREATE database apache_quetz;
CREATE database apache_quickstep_incubator;
CREATE database apache_ranger;
CREATE database apache_ratis_incubator;
CREATE database apache_rave;
CREATE database apache_reef;
CREATE database apache_ripple_incubator;
CREATE database apache_river;
CREATE database apache_rocketmq_incubator;
CREATE database apache_roller;
CREATE database apache_rya_incubator;
CREATE database apache_s2graph_incubator;
CREATE database apache_samoa_incubator;
CREATE database apache_samza;
CREATE database apache_santuario;
CREATE database apache_senssoft_incubator;
CREATE database apache_sentry;
CREATE database apache_serf;
CREATE database apache_servicemix;
CREATE database apache_shale;
CREATE database apache_shindig;
CREATE database apache_shiro;
CREATE database apache_singa_incubator;
CREATE database apache_sirona_incubator;
CREATE database apache_sis;
CREATE database apache_slider_incubator;
CREATE database apache_sling;
CREATE database apache_spamassassin;
CREATE database apache_spark;
CREATE database apache_spot_incubator;
CREATE database apache_sqoop;
CREATE database apache_stanbol;
CREATE database apache_stdcxx;
CREATE database apache_steve;
CREATE database apache_storm;
CREATE database apache_stratos;
CREATE database apache_stratosphere;
CREATE database apache_streams_incubator;
CREATE database apache_struts;
CREATE database apache_subversion;
CREATE database apache_superset_incubator;
CREATE database apache_synapse;
CREATE database apache_syncope;
CREATE database apache_systemml;
CREATE database apache_tajo;
CREATE database apache_tamaya_incubator;
CREATE database apache_tapestry;
CREATE database apache_taverna_incubator;
CREATE database apache_tcl;
CREATE database apache_tephra_incubator;
CREATE database apache_tez;
CREATE database apache_thrift;
CREATE database apache_tika;
CREATE database apache_tiles;
CREATE database apache_tinkerpop;
CREATE database apache_tomcat;
CREATE database apache_tomee;
CREATE database apache_toree_incubator;
CREATE database apache_trafficcontrol_incubator;
CREATE database apache_trafficserver;
CREATE database apache_trafodion_incubator;
CREATE database apache_turbine;
CREATE database apache_tuscany;
CREATE database apache_twill;
CREATE database apache_uima;
CREATE database apache_unomi_incubator;
CREATE database apache_usergrid;
CREATE database apache_vcl;
CREATE database apache_velocity;
CREATE database apache_vxquery;
CREATE database apache_weex_incubator;
CREATE database apache_whimsical;
CREATE database apache_whirr;
CREATE database apache_wicket;
CREATE database apache_wink;
CREATE database apache_wookie;
CREATE database apache_ws;
CREATE database apache_xalan;
CREATE database apache_xerces;
CREATE database apache_xml;
CREATE database apache_xmlbeans;
CREATE database apache_xmlgraphics;
CREATE database apache_yetus;
CREATE database apache_zeppelin;
CREATE database apache_zest;
CREATE database apache_zookeeper;


GRANT ALL PRIVILEGES ON `apache\_abdera`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_accumulo`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ace`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_activemq`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_airavata`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_airflow_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_allura`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ambari`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_annotator_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ant`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_any23`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_apex`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_apr`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_archiva`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_archive`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_argus`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ariatosca_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_aries`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_arrow`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_asf_wide`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_asterixdb`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_atlas`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_attic`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_aurora`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_avalon`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_avro`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_axis`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_bahir`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_batchee_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_beam`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_beehive`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_bigtop`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_bloodhound`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_bookkeeper`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_brooklyn`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_buildr`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_bval`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_calcite`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_camel`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_carbondata`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cassandra`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cayenne`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_celix`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_chemistry`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_chukwa`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_clerezza`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_click`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_climate`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cloudstack`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cmda_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cocoon`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_commons`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_commonsrdf`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_community`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_concerted_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_continuum`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cordova`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_corinthia_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cotton_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_couchdb`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_creadur`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_crunch`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ctakes`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_curator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_cxf`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_datafu_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_db`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_deltacloud`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_deltaspike`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_devicemap`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_directmemory`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_directory`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_distributedlog_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_drill`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_eagle`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_edgent_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_empire`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_esme`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_etch`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_excalibur`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_falcon`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_felix`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_fineract`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_fleece`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_flex`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_flink`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_flume`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_fluo_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_forrest`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_freemarker_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_gearpump_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_geode`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_geronimo`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_giraph`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_gobblin_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_gora`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_gossip_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_griffin_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_groovy`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_guacamole_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_gump`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hadoop`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hama`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_harmony`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hawq_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hbase`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hc`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hdt_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_helix`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hive`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hivemall_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_hivemind`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_horn_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_htrace_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_httpd`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ibatis`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ignite`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_impala_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_infra`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_iota_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_isis`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jackrabbit`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jakarta`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_james`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jclouds`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jena`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jmeter`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_johnzon`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_joshua_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_jspwiki`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_juddi`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_juneau_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_kafka`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_karaf`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_knox`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_kudu`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_kylin`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_labs`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_lens`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_lenya`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_libcloud`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_livy_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_logging`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_lucene`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_lucenenet`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_lucy`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_madlib_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mahout`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_manifoldcf`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_marmotta`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_maven`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mesos`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_metamodel`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_metron`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_milagro_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mina`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mnemonic_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mrql_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mrunit`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mxnet_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_myfaces`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_mynewt`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_myriad_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_netbeans_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_nifi`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_nutch`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ode`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ofbiz`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_olingo`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_oltu`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_omid_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_onami`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_oodt`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_oozie`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openaz_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openejb`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openjpa`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openmeetings`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_opennlp`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openoffice`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openwebbeans`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_openwhisk_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_optiq`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_orc`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_parquet`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_pdfbox`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_perl`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_phoenix`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_pig`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_pirk_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_pivot`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_poi`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_polygene`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ponymail_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_portals`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_predictionio_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_provisionr_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_pulsar_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_qpid`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_quarks`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_quetz`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_quickstep_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ranger`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ratis_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_rave`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_reef`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ripple_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_river`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_rocketmq_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_roller`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_rya_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_s2graph_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_samoa_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_samza`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_santuario`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_senssoft_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_sentry`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_serf`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_servicemix`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_shale`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_shindig`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_shiro`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_singa_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_sirona_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_sis`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_slider_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_sling`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_spamassassin`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_spark`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_spot_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_sqoop`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_stanbol`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_stdcxx`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_steve`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_storm`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_stratos`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_stratosphere`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_streams_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_struts`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_subversion`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_superset_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_synapse`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_syncope`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_systemml`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tajo`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tamaya_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tapestry`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_taverna_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tcl`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tephra_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tez`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_thrift`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tika`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tiles`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tinkerpop`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tomcat`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tomee`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_toree_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_trafficcontrol_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_trafficserver`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_trafodion_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_turbine`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_tuscany`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_twill`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_uima`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_unomi_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_usergrid`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_vcl`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_velocity`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_vxquery`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_weex_incubator`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_whimsical`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_whirr`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_wicket`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_wink`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_wookie`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_ws`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_xalan`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_xerces`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_xml`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_xmlbeans`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_xmlgraphics`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_yetus`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_zeppelin`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_zest`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `apache\_zookeeper`.* TO 'jhartmann'@'%'WITH GRANT OPTION;
